import * as yup from "yup";

export const ApplySchema = yup.object().shape({
  firstName: yup.string().required("First name is required"),
  middleName: yup.string(),
  lastName: yup.string().required("Last name is required"),
  motherMaidenName: yup.string().required("Mother's maiden name is required"),
  streetAddress: yup.string().required("Street address is required"),
  streetAddress2: yup.string(),
  city: yup.string().required("City is required"),
  state: yup.string().required("State / Province is required"),
  country: yup.string().required("Country is required"),
  email: yup.string().email("Please enter a valid email").required("Email is required"),
  phoneNumber: yup.string().required("Phone number is required"),
  gender: yup.string().required("Gender is required"),
  maritalStatus: yup.string().required("Marital status is required"),
  applicationReason: yup.string().required("Reason for application is required"),
  amountPreferred: yup.string().required("Preferred amount is required"),
  doYouWork: yup.string().required("Please select your employment status"),
  occupation: yup.string(),
  annualIncome: yup.string().required("Annual income is required"),
  ssnEin: yup.string().required("SSN / EIN is required"),
  driverLicense: yup.string().required("Driver's license number is required"),
  disbursementMethod: yup.string().required("Preferred disbursement method is required"),
  overviewReason: yup.string().required("Overview of reason for application is required"),
});
